name: Deploy Mini Todo API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/mini-todo-api
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart mini-todo-api
            sudo systemctl status mini-todo-api --no-pager
